# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dfda675aac67276a4576d855189c61ce66054be13245b35f74fd300e49a36558132500806bb17157d9864e967f028209c148e060d7f5907e9835db8bd9a820ce

test:
  secret_key_base: 9ed3cdb9cb6ceb72fa64f5a0531d12f988788994c24e0930a1f1d3094df84ce005d1a5e9e0500dec1ee50e949e47e33c38d7e9b809d87141eb57ce11b4a1032a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
